"""
Django settings for webhoconline project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zx7y@i1aq7y%62c)m!$c#%d7-5l_3#dqhvim9(ndzm)5+76f(='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webhoconline.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'app.context_processors.cart_count',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webhoconline.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'WebHocTap_Moi',  # <--- Thay tên này bằng tên Database bạn đã tạo ở Bài 1
        'USER': '',             # Để trống
        'PASSWORD': '',         # Để trống
        'HOST': r'DESKTOP-CU99I1G\SQLEXPRESS',    # Hoặc tên máy chủ SQL của bạn
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Nơi chứa các file CSS/JS tự viết của dự án
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
LOGIN_REDIRECT_URL = 'home'  # Đăng nhập xong về trang chủ
LOGOUT_REDIRECT_URL = 'home' # Đăng xuất xong về trang chủ
LOGIN_URL = 'login'          # Chưa đăng nhập thì đá về trang login
AUTH_USER_MODEL = 'app.User'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# CẤU HÌNH ĐỊNH DẠNG SỐ VÀ TIỀN TỆ CHO TIẾNG VIỆT
USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = '.'
DECIMAL_SEPARATOR = ','
NUMBER_GROUPING = 3
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'hdtrung1712@gmail.com' # Ví dụ thế này # Thay bằng Gmail của bạn
EMAIL_HOST_PASSWORD = 'lmyy wdmj rrfl umuk'
BANK_CODE = 'MB'
BANK_ACCOUNT_NUMBER = '0916536176'
BANK_ACCOUNT_NAME = 'HA DUC TRUNG'
# ==========================================
# CẤU HÌNH GIAO DIỆN ADMIN JAZZMIN
# ==========================================
# ==========================================
# CẤU HÌNH GIAO DIỆN ADMIN JAZZMIN
# ==========================================
JAZZMIN_SETTINGS = {
    # Thông tin cơ bản
    "site_title": "Admin Khóa Học",
    "site_header": "Hệ Thống Quản Trị",
    "site_brand": "Học Trực Tuyến",
    "welcome_sign": "Chào mừng bạn đã quay trở lại!",
    "copyright": "Học Lập Trình - Phát triển bởi Trung",
    "show_version": False,
    "show_ui_builder": False, # Đổi thành False để tắt cái bảng Customize bên trái
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    # Cài đặt Icon cho thanh Menu bên trái (Dùng thư viện FontAwesome)
    "icons": {
        "auth.Group": "fas fa-users-cog",
        "app.User": "fas fa-user-graduate",       # Icon học viên
        "app.Category": "fas fa-layer-group",     # Icon danh mục
        "app.Course": "fas fa-book-open",         # Icon khóa học sách mở
        "app.Lesson": "fas fa-play-circle",       # Icon bài giảng video
        "app.Order": "fas fa-shopping-cart",      # Icon giỏ hàng/đơn hàng
        "app.Roadmap": "fas fa-map-signs",        # Icon lộ trình
    },
    
    # Bo góc các nút bấm cho hiện đại
    "button_classes": {
        "primary": "btn-primary rounded-pill",
        "secondary": "btn-secondary rounded-pill",
    },
}

# Cấu hình màu sắc mặc định (Tone tối sang trọng)
# Cấu hình màu sắc nâng cao (Theme hiện đại, nút bo tròn nhẹ)
JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-white navbar-light", # Thanh điều hướng trên cùng sáng sủa
    "font_family": "Segoe UI, Tahoma, Geneva, Verdana, sans-serif",
    "theme": "litera", # Giao diện tối giản, sang trọng
    "sidebar": "sidebar-dark-primary", # Cột trái màu tối để làm nổi bật Menu
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True, # Thu gọn khoảng cách menu cho tinh tế
    "accent": "accent-primary",
    
    # Nút bấm có màu sắc chuẩn xác
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}