# Generated by Django 5.2.10 on 2026-01-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng (COD)'), ('banking', 'Chuyển khoản ngân hàng')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang xử lý'), ('completed', 'Đã hoàn thành'), ('canceled', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
