# Generated by Django 5.2.10 on 2026-01-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_instructor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'Giảng viên', 'verbose_name_plural': 'Danh sách Giảng viên'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Quản lý Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Chi tiết đơn hàng', 'verbose_name_plural': 'Chi tiết các đơn hàng'},
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên lộ trình')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, null=True, upload_to='roadmaps/', verbose_name='Ảnh đại diện')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(related_name='roadmaps', to='app.course', verbose_name='Các khóa học trong lộ trình')),
            ],
            options={
                'verbose_name': 'Lộ trình',
                'verbose_name_plural': 'Quản lý Lộ trình',
            },
        ),
    ]
