# Generated by Django 5.2.10 on 2026-01-21 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_instructor_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề bài học')),
                ('video_id', models.CharField(max_length=100, verbose_name='Youtube Video ID')),
                ('duration', models.FloatField(default=0.0, verbose_name='Thời lượng (phút)')),
                ('order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='app.course')),
            ],
            options={
                'verbose_name': 'Bài học',
                'verbose_name_plural': 'Danh sách Bài học',
                'ordering': ['order'],
            },
        ),
    ]
