# Generated by Django 5.2.10 on 2026-01-23 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_lessonreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'verbose_name': 'Người dùng'},
        ),
    ]
