# Generated by Django 5.2.10 on 2026-02-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_options'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện'),
        ),
       # migrations.AddField(
        #    model_name='user',
        #    name='groups',
         #   field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        #),
#        migrations.AddField(
 #           model_name='user',
  #          name='user_permissions',
   #         field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
    #    ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Đang xử lý'), ('Completed', 'Đã hoàn thành'), ('Canceled', 'Đã hủy')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Học viên'), ('teacher', 'Giảng viên')], default='student', max_length=20, verbose_name='Vai trò'),
        ),
    ]
