# Generated by Django 5.2.10 on 2026-04-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_order_is_hidden_user_groups_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_hidden',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Chờ thanh toán'), ('Processing', 'Đang chờ duyệt'), ('Completed', 'Đã hoàn thành'), ('Canceled', 'Đã hủy')], default='Pending', max_length=20),
        ),
    ]
